### ISSUE TITLE
delete \ensuremath

### ISSUE THREAD

**Issue by davidfarmer** [jthomasbarry/aafmt#1]
From line 1346 of complex.tex, and wherever else it appears in the source files.

**Comment by jthomasbarry** [comment]
This is the only place I found this used. It should be fixed now.

**Comment by davidfarmer** [comment]
It seems to be there in the list at the beginning of
3.3.6A Remark on representations of complex numbers

**Comment by christhron** [comment]
I've looked in the Latex code, and there are no more explicit \ensuremath's.  Is it possible that it's calling a routine?

**Comment by davidfarmer** [comment]
The \ensuremath was explicitly writen in the LaTeX source.

Either you missed it the first time, or some merge made the
first change go away.
